Astractl 27293 updates for releae branche
NetApp/astra-connector-operator pull request #30
Opened 2023-06-09 20:51 UTC by jharrod

Updates versioning/tagging in connector operator repo.

Versioning file now has all three digits - X.Y.Z

For release branches versions and tags look like
- "1.2.3-202305102210"

For non-release branches:
BUILD-BRANCH (BUILD is currently a timestamp)

2023-06-09 20:57 UTC, jharrod commented on scripts/create-image-tar.sh
> -pattern=' +image: netapp\/astra-connector-operator:([^\n ]*)'
Not sure why this wasn't working, it was cutting off the end of my version when it was in the BUILD-BRANCH form

2023-06-09 20:58 UTC, jharrod commented on Makefile
> -docker-push-base:
These were not used as far as I could tell, and were confusing, so I removed them

2023-06-09 21:27 UTC, raghu-sarangapani approved these changes

2023-06-12 17:16 UTC, josecrosa commented
typo in PR title: releae > release

2023-06-12 21:09 UTC, bmason42 requested changes

2023-06-12 21:09 UTC, bmason42 commented on version.txt
> +2.1.0
We need to pop this to 3.0.0
We already have a 2 series and this is a breakingish change

2023-06-13 15:35 UTC, bmason42 approved these changes

2023-06-13 17:13 UTC, merged